---
- name: Создать директорию для Element JWT
  ansible.builtin.file:
    path: "{{ element_jwt_root }}"
    state: directory
    owner: "{{ matrix_system_user }}"
    group: "{{ matrix_system_group }}"
    mode: "0750"

- name: Запустить сервис Element JWT
  community.docker.docker_container:
    name: element-jwt
    image: "{{ element_jwt_image }}"
    restart_policy: always
    pull: true
    networks:
      - name: "{{ docker_network_name }}"
    published_ports:
      - "127.0.0.1:{{ element_jwt_port }}:8080"
    env:
      LIVEKIT_URL: "wss://{{ matrix_domains.livekit }}/livekit/sfu"
      LIVEKIT_KEY: "{{ livekit_api_key }}"
      LIVEKIT_SECRET: "{{ livekit_api_secret }}"
      LIVEKIT_JWT_PORT: "8080"
      LIVEKIT_FULL_ACCESS_HOMESERVERS: "{{ element_jwt_full_access_homeservers | join(',') }}"
    state: started
  register: element_jwt_container
